### ISSUE TITLE
Cadastrar local

### ISSUE THREAD

**Issue by OscarDeBrito** [ResidenciaTICBrisa/T2G3-Sistema-Instalacao-Eletrica#10]
Como usuário autenticado, quero poder registrar um novo local no aplicativo para poder gerenciá-lo.

#### Critérios de aceitação:
- [x] Atributos obrigatórios: `nome, longitude, latitude, dono do lugar`
- [x] O `dono` deve ser definido automaticamente como o usuário autenticado no sistema.

**Comment by AlefMemTav** [comment]
Rota: http://10.0.2.2:8000/api/places/
