### ISSUE TITLE
Realizar login

### ISSUE THREAD

**Issue by OscarDeBrito** [ResidenciaTICBrisa/T2G3-Sistema-Instalacao-Eletrica#11]
Como usuário, quero poder fazer login com segurança para  ter acesso as informações no aplicativo.

### Critérios de aceitação 

- [x] O login é feito com `nome de usuário, senha`;
- [x] Caso o usuário insira credenciais inválidas, deve ser exibida uma mensagem de erro indicando que o login falhou;
- [x] Após o login bem-sucedido, o usuário deve ser redirecionado para a página inicial;

**Comment by AlefMemTav** [comment]
@EngDann http://127.0.0.1:8000/api/login/
