### ISSUE TITLE
Cadastrar area

### ISSUE THREAD

**Issue by OscarDeBrito** [ResidenciaTICBrisa/T2G3-Sistema-Instalacao-Eletrica#13]
Como usuário, quero poder adicionar uma area dentro de cada local para registrar as instalações elétricas daquela area.

#### Critérios de aceitação:
- [x] Atributos obrigatórios: `id, nome, andar, local`;

<!-- data de criação --!>

**Comment by AlefMemTav** [comment]
Nós refatoramos o conceito de sala (room) para area, pois é mais abrangente.

**Comment by AlefMemTav** [comment]
Não deve ser usado select em andar, mas sim um campo numérico, para o usuário informar o andar. Se for 0 é térreo, se 1, primerio andar, etc.

**Comment by AlefMemTav** [comment]
Rota: http://10.0.2.2:8000/api/areas/
