### ISSUE TITLE
Excluir area

### ISSUE THREAD

**Issue by OscarDeBrito** [ResidenciaTICBrisa/T2G3-Sistema-Instalacao-Eletrica#69]
Como usuário, quero poder excluir  informações das áreas, caso haja necessidade de não manter as informações.

### Critérios de aceitação 
- [ ]  Ao selecionar a opção de exclusão da area, o usuário deve ser solicitado a confirmar sua escolha;
- [x] Após a confirmação da exclusão da area, todos os dados da area devem ser removidos do sistema, como as informações que tinha sobre sistemas elétricos pertecentes a ela;
- [x] A area deve ser excluída da lista de areas do local responsável por ela;

**Comment by AlefMemTav** [comment]
Rota: http://10.0.2.2:8000/api/areas/pk
