### ISSUE TITLE
Excluir local

### ISSUE THREAD

**Issue by OscarDeBrito** [ResidenciaTICBrisa/T2G3-Sistema-Instalacao-Eletrica#70]
Como usuário, quero poder excluir  informações de locais, caso haja necessidade de tirar informações do sistema.

### Critérios de aceitação:
- [ ]  Ao selecionar a opção de exclusão do local, o usuário deve ser solicitado a confirmar sua escolha;
- [x] Após a confirmação da exclusão do local, todos os dados do local devem ser removidos do sistema, como as informações que tinha sobre sistemas elétricos pertecentes a ela (areas e andares);
- [x] O local deve ser excluído da lista de locais do dono do local;

**Comment by AlefMemTav** [comment]
Rota: http://10.0.2.2:8000/api/places/pk
