### ISSUE TITLE
Vizualizar area

### ISSUE THREAD

**Issue by OscarDeBrito** [ResidenciaTICBrisa/T2G3-Sistema-Instalacao-Eletrica#72]
Como usuário, desejo visualizar as áreas que eu criei para revisar seu status e detalhes.

#### Critérios de aceitação:
- [x] Deve-se visualizar as informações: `nome, andar, lugar`.

**Comment by AlefMemTav** [comment]
Rota: http://10.0.2.2:8000/api/areas/<pk>
