### ISSUE TITLE
Cadastrar equipamento

### ISSUE THREAD

**Issue by OscarDeBrito** [ResidenciaTICBrisa/T2G3-Sistema-Instalacao-Eletrica#73]
Como usuário autenticado, quero poder registrar um novo equipamento no aplicativo para poder gerenciá-lo.

#### Critérios de aceitação:
- [x] Atributos obrigatórios: `nome, tipo de equipamento`;
- [x] Atributos opcionais: `foto`, `descrição`.
- [x] O `dono` deve ser definido automaticamente como o usuário autenticado no sistema;

**Comment by AlefMemTav** [comment]
Rota: http://10.0.2.2:8000/api/equipments/
