### ISSUE TITLE
Excluir equipamento

### ISSUE THREAD

**Issue by OscarDeBrito** [ResidenciaTICBrisa/T2G3-Sistema-Instalacao-Eletrica#74]
Como usuário, quero poder excluir um equipamento, caso haja necessidade de tirar equipamentos do sistema.

### Critérios de aceitação 
- [x]  Ao selecionar a opção de exclusão do equipamento, o usuário deve ser solicitado a confirmar sua escolha;
- [x] Após a confirmação da exclusão do equipamento, todos os dados do equipamento devem ser removidos do sistema, como as informações de foto com a descrição, nome e tipo;
- [x] Os equipamentes que estão vinculadas a algumas sala devem se manter nela independente de ter sido excluído do sistema;

**Comment by AlefMemTav** [comment]
Rota: http://10.0.2.2:8000/api/equipments/pk
