### ISSUE TITLE
Visualizar equipamento

### ISSUE THREAD

**Issue by OscarDeBrito** [ResidenciaTICBrisa/T2G3-Sistema-Instalacao-Eletrica#75]
Como usuário, desejo visualizar uma  todos  os equipamentos que criei e visualizar todos os equipamentos padrões para revisar seu status e detalhes.

#### Critérios de aceitação:
- [x] Deve-se visualizar as informações `nome, tipo, foto, descrição`.

**Comment by AlefMemTav** [comment]
Rota: http://10.0.2.2:8000/api/equipments/pk
