### ISSUE TITLE
Editar equipamento

### ISSUE THREAD

**Issue by OscarDeBrito** [ResidenciaTICBrisa/T2G3-Sistema-Instalacao-Eletrica#76]
Como usuário, quero poder editar  informações do  equipamento caso haja necessidade de atualização.

#### Critérios de aceitação:
- [x] Editar atributos editáveis: `nome, tipo de equipamento, foto, descrição`;

**Comment by AlefMemTav** [comment]
Rota: http://10.0.2.2:8000/api/equipments/pk
